# Generated by Django 2.2.3 on 2019-07-15 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('regTime', models.DateTimeField(auto_now_add=True, verbose_name='regTime')),
                ('courseCnt', models.IntegerField(default=0, verbose_name='courseCnt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='jwcAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwcNumber', models.TextField(verbose_name='jwcNumber')),
                ('jwcPasswd', models.TextField(verbose_name='jwcPasswd')),
                ('jwcCookie', models.TextField(verbose_name='jwcCookie')),
                ('jwcBelongto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SCUKiller.UserProfile')),
            ],
            options={
                'verbose_name': 'jwcAccount',
            },
        ),
        migrations.CreateModel(
            name='coursesWatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=100, verbose_name='courseName')),
                ('kch', models.CharField(default='', max_length=100, verbose_name='kch')),
                ('kxh', models.CharField(default='', max_length=100, verbose_name='kxh')),
                ('startTime', models.DateTimeField(auto_now_add=True, verbose_name='startTime')),
                ('attempts', models.IntegerField(default=0, verbose_name='attempts')),
                ('isSuccess', models.BooleanField(default=False, verbose_name='isSuccess')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesHost', to='SCUKiller.UserProfile')),
            ],
            options={
                'verbose_name': 'coursesWatching',
            },
        ),
    ]
