# Generated by Django 2.1.8 on 2020-03-10 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000, verbose_name='神秘代码')),
                ('points', models.FloatField(default=10.0, verbose_name='点数')),
                ('usedBy', models.CharField(default='', max_length=1000, verbose_name='被谁使用')),
                ('addBy', models.CharField(default='', max_length=1000, verbose_name='由谁加入')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('usedTime', models.CharField(max_length=1000, verbose_name='使用时间')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='等待中', max_length=100, verbose_name='状态')),
                ('inq', models.BooleanField(default=False, verbose_name='正在队列中')),
                ('keyword', models.CharField(default='', max_length=50, verbose_name='关键词')),
                ('kcm', models.CharField(default='', max_length=100, verbose_name='课程名')),
                ('kch', models.CharField(default='', max_length=100, verbose_name='课程号')),
                ('kxh', models.CharField(default='', max_length=100, verbose_name='课序号')),
                ('type', models.CharField(default='自由选课', max_length=10, verbose_name='课程类型')),
                ('term', models.CharField(default='2019-2020-1-1', max_length=100, verbose_name='学期')),
                ('teacher', models.TextField(default='', max_length=1000, verbose_name='授课老师')),
                ('campus', models.CharField(default='', max_length=100, verbose_name='校区')),
                ('location', models.CharField(default='', max_length=100, verbose_name='上课地点')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('attempts', models.IntegerField(default=0, verbose_name='尝试次数')),
                ('isSuccess', models.IntegerField(default=0, verbose_name='是否成功')),
                ('gid', models.CharField(default='', max_length=100, verbose_name='组编号')),
                ('latestRemaining', models.IntegerField(default=0, verbose_name='最新剩余课余量')),
            ],
            options={
                'verbose_name': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='GlobalConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('notiTime', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
                ('isRead', models.BooleanField(default=False, verbose_name='是否阅读')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notificationHost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=100, verbose_name='支付方式')),
                ('trade_no', models.CharField(default='', max_length=100, verbose_name='商户单号')),
                ('platform_no', models.CharField(default='', max_length=100, verbose_name='第三方平台单号')),
                ('payment_tool_no', models.CharField(default='', max_length=100, verbose_name='用户支付工具单号')),
                ('body', models.CharField(default='', max_length=1000, verbose_name='订单标题')),
                ('total_fee', models.FloatField(verbose_name='订单金额')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('payTime', models.CharField(max_length=1000, verbose_name='订单支付时间')),
                ('closedTime', models.CharField(max_length=1000, verbose_name='订单关闭时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('telephone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('regTime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('points', models.FloatField(default=10.0, verbose_name='点数')),
                ('courseCnt', models.IntegerField(default=0, verbose_name='已添加课程数目')),
                ('courseRemainingCnt', models.IntegerField(default=0, verbose_name='剩余课程权限')),
            ],
            options={
                'verbose_name': '用户个人信息',
            },
        ),
        migrations.CreateModel(
            name='jwcAccount',
            fields=[
                ('jwcNumber', models.CharField(max_length=100, verbose_name='学号')),
                ('jwcPasswd', models.CharField(max_length=256, verbose_name='密码')),
                ('jwcCookie', models.CharField(max_length=256, verbose_name='Cookie')),
                ('proxy', models.CharField(default='', max_length=100, verbose_name='代理IP')),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='SCUKiller.UserProfile')),
            ],
            options={
                'verbose_name': '教务处账号信息',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coursesHost', to='SCUKiller.UserProfile'),
        ),
    ]
