# Generated by Django 2.2.3 on 2019-08-12 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SCUKiller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwcaccount',
            name='id',
        ),
        migrations.AddField(
            model_name='courses',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coursesHost', to='SCUKiller.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jwcaccount',
            name='userprofile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='SCUKiller.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notificationHost', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
