# Generated by Django 2.2.3 on 2019-08-20 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SCUKiller', '0002_auto_20190812_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=100, verbose_name='支付方式')),
                ('trade_no', models.CharField(default='', max_length=100, verbose_name='商户单号')),
                ('platform_no', models.CharField(default='', max_length=100, verbose_name='第三方平台单号')),
                ('body', models.CharField(default='', max_length=1000, verbose_name='订单标题')),
                ('total_fee', models.FloatField(verbose_name='订单金额')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
