# Generated by Django 2.2.3 on 2019-08-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCUKiller', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
    ]
