# Generated by Django 2.2.3 on 2019-08-20 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SCUKiller', '0004_remove_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
