# Generated by Django 2.2.3 on 2019-08-20 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SCUKiller', '0006_auto_20190820_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='addTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='订单生成时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='payTime',
            field=models.CharField(default=1, max_length=1000, verbose_name='订单支付时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_tool_no',
            field=models.CharField(default='', max_length=100, verbose_name='用户支付工具单号'),
        ),
    ]
