# Generated by Django 2.2.3 on 2019-08-20 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SCUKiller', '0007_auto_20190820_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='closedTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='订单关闭时间'),
            preserve_default=False,
        ),
    ]
