# Generated by Django 2.2.3 on 2019-08-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCUKiller', '0008_orders_closedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='gid',
            field=models.CharField(default='', max_length=100, verbose_name='组编号'),
        ),
    ]
