# Generated by Django 2.2.3 on 2019-09-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCUKiller', '0010_auto_20190918_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.FloatField(default=10.0, verbose_name='点数'),
        ),
    ]
