# Generated by Django 2.2.5 on 2019-12-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCUKiller', '0011_auto_20190919_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='latestRemaining',
            field=models.IntegerField(default=0, verbose_name='最新剩余课余量'),
        ),
    ]
